# This script build Exiled and LabAPI version of HSM and release both DLLs with release note.
name: Test

on:
  push:
    tags:
      - 'v*'
      - 'V*'

jobs:
  Test:
    runs-on: windows-latest

    steps:
    - name: Get tag name
      id: get_tag
      shell: bash
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Get commit message
      id: get_commit_msg
      shell: bash
      run: |
        echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
        git log -1 --pretty=%B >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Debug tag
      run: echo "${{ steps.get_tag.outputs.tag }}"
    - name: Debug commit msg
      run: echo "${{ steps.get_commit_msg.outputs.commit_msg }}"
